micronaut:
  application:
    name: agenticchat
  server:
    port: 8080
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        descriptions: true
        step: PT1M

endpoints:
  health:
    enabled: true
    sensitive: false
    details-visible: ANONYMOUS
  prometheus:
    enabled: true
    sensitive: false
